### ISSUE TITLE
little typo/error that could be a problem

### ISSUE THREAD

**Issue by AJGQ** [barbosamarco4/safe_turtles#1]
Hi Marco it's Artur that was on the meeting for the SAFE project.

When checking out the code to use it as an example I catched an error I think, and it is so subtle that I needed to talk about it, in the `safety_controller.cpp` in line 60 the condition has a `,2` that I think you didn't intend to put it.

**Comment by barbosamarco4** [comment]
Thanks! It was indeed an error. Just fixed it
